[package]
name = "calc-service"
version = "0.1.0"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[[bin]]
name = "calc_service"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = { version="0.6.15", features = ["logger"] }
log = "0.4.14"
